---

- name: Make sure essential software is installed
  yum:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - bootstrap_base_packages
    - bootstrap_packages

- name: Create specified system groups
  group:
    name: '{{ item }}'
    state: 'present'
    system: True
  with_items: bootstrap_admin_groups
  when: bootstrap_admin is defined and bootstrap_admin | bool

- name: Check if potential administrator account exists
  shell: getent passwd {{ bootstrap_admin_name }} || true
  register: bootstrap_register_admin_account
  when: not bootstrap_admin_manage_existing
  changed_when: False
  always_run: yes

- name: Set admin manage existing to true
  set_fact:
    bootstrap_register_admin_account:
      stdout: False
  when: bootstrap_admin_manage_existing

- name: Create administrator group (system)
  group:
    name: '{{ bootstrap_admin_name }}'
    state: 'present'
    system: True
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and bootstrap_admin_system | bool))

- name: Create administrator group (normal)
  group:
    name: '{{ bootstrap_admin_name }}'
    state: 'present'
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and not bootstrap_admin_system | bool))

- name: Create administrator account (system)
  user:
    name: '{{ bootstrap_admin_name }}'
    state: 'present'
    system: True
    group: '{{ bootstrap_admin_name }}'
    groups: '{{ bootstrap_admin_groups | join(",") }}'
    append: True
    home: '{{ bootstrap_admin_system_home }}'
    shell: '{{ bootstrap_admin_shell }}'
    comment: '{{ bootstrap_admin_comment }}'
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and bootstrap_admin_system | bool))

- name: Create administrator account (normal)
  user:
    name: '{{ bootstrap_admin_name }}'
    state: 'present'
    group: '{{ bootstrap_admin_name }}'
    groups: '{{ bootstrap_admin_groups | join(",") }}'
    append: True
    home: '{{ bootstrap_admin_home }}'
    shell: '{{ bootstrap_admin_shell }}'
    comment: '{{ bootstrap_admin_comment }}'
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and not bootstrap_admin_system | bool))

- name: Set admin home directory group and permissions (system)
  file:
    path: '{{ bootstrap_admin_system_home }}'
    group: '{{ bootstrap_admin_home_group }}'
    mode: '{{ bootstrap_admin_home_mode }}'
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and bootstrap_admin_system | bool))

- name: Set admin home directory group and permissions (normal)
  file:
    path: '{{ bootstrap_admin_home }}'
    group: '{{ bootstrap_admin_home_group }}'
    mode: '{{ bootstrap_admin_home_mode }}'
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_register_admin_account is defined and not bootstrap_register_admin_account.stdout) and
         (bootstrap_admin_system is defined and not bootstrap_admin_system | bool))

- name: Install ssh public key on root account
  authorized_key:
    user: 'root'
    key: '{{ "\n".join(bootstrap_admin_sshkeys) | string }}'
    state: 'present'
  failed_when: (bootstrap_admin_sshkeys is undefined or
                (bootstrap_admin_sshkeys is defined and not bootstrap_admin_sshkeys))

- name: Install ssh public key on administrator account
  authorized_key:
    user: '{{ bootstrap_admin_name }}'
    key: '{{ "\n".join(bootstrap_admin_sshkeys) | string }}'
    state: 'present'
  when: bootstrap_admin is defined and bootstrap_admin | bool
  failed_when: (bootstrap_admin_sshkeys is undefined or
                (bootstrap_admin_sshkeys is defined and not bootstrap_admin_sshkeys))

- name: Configure system group with paswordless access in sudo
  lineinfile:
    dest: '/etc/sudoers.d/{{ bootstrap_sudo_group }}'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: 'present'
    create: True
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: 'visudo -cf %s'
  with_items:
    - regexp: '^Defaults: %{{ bootstrap_sudo_group }} env_check\s'
      line:    'Defaults: %{{ bootstrap_sudo_group }} env_check += "SSH_CLIENT"'
    - regexp: '^%{{ bootstrap_sudo_group }}\s'
      line:    '%{{ bootstrap_sudo_group }} ALL = (ALL:ALL) NOPASSWD: SETENV: ALL'
  when: bootstrap_sudo is defined and bootstrap_sudo | bool

- name: Ensure /etc/sudoers includes /etc/sudoers.d
  lineinfile:
    dest: '/etc/sudoers'
    regexp: '^#includedir\s+/etc/sudoers.d$'
    line: '#includedir /etc/sudoers.d'
    state: 'present'
    validate: 'visudo -cf %s'

- name: Make sure that administrator account is in passwordless sudo group
  user:
    name: '{{ bootstrap_admin_name }}'
    state: 'present'
    groups: '{{ bootstrap_sudo_group }}'
    append: True
  when: ((bootstrap_admin is defined and bootstrap_admin | bool) and
         (bootstrap_sudo is defined and bootstrap_sudo | bool))

- name: Enforce new hostname
  hostname:
    name: '{{ bootstrap_hostname }}'

- name: Save hostname in /etc/sysconfig/network
  lineinfile:
    dest: '/etc/sysconfig/network'
    line: 'HOSTNAME={{ bootstrap_hostname }}'

- name: Save hostname and domain in /etc/hosts
  lineinfile:
    state: 'present'
    dest: '/etc/hosts'
    regexp: '{{ "^" + (bootstrap_ipv4 | default("127.0.1.1")) | replace(".","\.") }}'
    line: '{{ (bootstrap_ipv4 | default("127.0.1.1")) + "\t" + (((bootstrap_hostname | d(ansible_hostname)) + "." + bootstrap_domain + "\t" + (bootstrap_hostname | d(ansible_hostname))) if bootstrap_domain|d() else (bootstrap_hostname | d(ansible_hostname))) }}'

